set(sources
        compute_instance.hpp
        pipeline_dynamic_state.hpp
        pipeline_state.cpp
        pipeline_state.h
        framebuffer_config.hpp
        framebuffer_config.cpp
        fsr.cpp
        fsr.h
        graphic.hpp
        render_base.cpp
        render_base.hpp
        render_core.hpp
        render_core.cpp
        shader_cache.hpp
        shader_cache.cpp
        shader_notify.cpp
        shader_notify.hpp
        surface.cpp
        surface.hpp
        texture.hpp
        types.hpp
        vertex.hpp
        buffer_cache/buffer_base.hpp
        buffer_cache/buffer_cache.h
        buffer_cache/buffer_cache_base.hpp
        render_vulkan/blit_screen.cpp
        render_vulkan/buffer_cache.cpp
        render_vulkan/command_pool.cpp
        render_vulkan/compute_pipeline.cpp
        render_vulkan/descriptor_pool.cpp
        render_vulkan/format_to_vk.cpp
        render_vulkan/graphics_pipeline.cpp
        render_vulkan/master_semaphore.cpp
        render_vulkan/pipeline_cache.cpp
        render_vulkan/pipeline_cache.cppm
        render_vulkan/present_manager.cpp
        render_vulkan/render_pass.cpp
        render_vulkan/render_pass.cppm
        render_vulkan/render_vulkan.cpp
        render_vulkan/resource_pool.cpp
        render_vulkan/scheduler.cpp
        render_vulkan/staging_buffer_pool.cpp
        render_vulkan/swapchain.cpp
        render_vulkan/texture_cache.cpp
        render_vulkan/update_descriptor.cpp
        render_vulkan/vk_graphic.cpp
        render_vulkan/vk_graphic.cppm
        render_vulkan/vk_imgui.cpp
        render_vulkan/present/filters.cpp
        render_vulkan/present/fsr.cpp

        render_vulkan/present/vulkan_utils.cpp
        render_vulkan/present/window_adapt_pass.cpp
        texture/formatter.cpp
        texture/formatter.h
        texture/image_info.hpp
        texture/image_view_base.cpp
        texture/image_view_base.hpp
        texture/image_view_info.cpp
        texture/image_view_info.hpp
        texture/render_targets.h
        texture/samples_helper.h
        texture/texture.hpp
        texture/types.hpp
        texture_cache/texture_cache.h
        texture_cache/texture_cache_base.hpp
        texture_cache/utils.cpp
        texture_cache/utils.hpp
        vulkan_common/debug_callback.cpp
        vulkan_common/device_utils.cpp
        vulkan_common/vk_instance.cpp
        vulkan_common/vk_device.cpp
        vulkan_common/memory_allocator.cpp
        vulkan_common/vk_surface.cpp
        vulkan_common/vma.cpp
        vulkan_common/vma.hpp
        vulkan_common/vulkan_common.hpp
        vulkan_common/vulkan_wrapper.cpp
        render_vulkan/present/layer.cpp

)

set(MODULE_FILES
        compute_instance.cppm
        fsr.cppm
        render_base.cppm
        render_core.cppm
        pipeline_state.cppm
        framebuffer_config.cppm
        shader_cache.cppm
        mesh.cppm
        graphic.cppm
        shader_notify.cppm
        types.cppm
        texture.cppm

        vulkan_common/debug_callback.cppm
        vulkan_common/vk_instance.cppm
        vulkan_common/vk_common.cppm
        vulkan_common/vk_surface.cppm
        vulkan_common/vk_device.cppm
        vulkan_common/device_utils.cppm
        vulkan_common/vulkan_wrapper.cppm
        vulkan_common/memory_allocator.cppm
        render_vulkan/vk_imgui.cppm
        render_vulkan/vk_shader_util.cppm
        render_vulkan/present/vulkan_utils.cppm
        render_vulkan/present/fsr.cppm
        render_vulkan/present/present_frame.cppm
        render_vulkan/present/layer.cppm
        render_vulkan/present/present_push_constants.cppm
        render_vulkan/present/anti_alias_pass.cppm
        render_vulkan/present/window_adapt_pass.cppm
        render_vulkan/present/filters.cppm

        render_vulkan/blit_screen.cppm
        render_vulkan/buffer_cache.cppm
        render_vulkan/command_pool.cppm
        render_vulkan/compute_pipeline.cppm
        render_vulkan/descriptor_pool.cppm
        render_vulkan/format_to_vk.cppm
        render_vulkan/master_semaphore.cppm
        render_vulkan/graphics_pipeline.cppm
        render_vulkan/pipeline_cache.cppm
        render_vulkan/present_manager.cppm
        render_vulkan/render_pass.cppm
        render_vulkan/render_vulkan.cppm
        render_vulkan/resource_pool.cppm
        render_vulkan/pipeline_helper.cppm
        render_vulkan/scheduler.cppm
        render_vulkan/staging_buffer_pool.cppm
        render_vulkan/swapchain.cppm
        render_vulkan/texture_cache.cppm
        render_vulkan/update_descriptor.cppm
        render_vulkan/vk_render.cppm
        render_vulkan/vk_graphic.cppm


)
