set(sources
    alignment.h
    alignment.hpp
    assert.hpp
    bit_cast.h
    bit_field.hpp
    bit_util.h
    common_funcs.hpp
    common_types.hpp
    div_ceil.hpp
    error.hpp
    error.cpp
    file.cpp
    file.hpp
    literals.hpp
    logger.hpp
    logger.cpp
    math_util.h
    polyfill_thread.hpp
    scope_exit.h
    settings_common.hpp
    settings_common.cpp
    settings_setting.hpp
    settings_enums.hpp
    settings.hpp
    settings.cpp
    slot_vector.hpp
    swap.h
    thread_worker.hpp
    thread.hpp
    thread.cpp
    unique_function.h
)

set(MODULE_FILES
        logger.cppm # 模块接口文件
)
